# Generated by Django 4.0.3 on 2022-04-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('phone_No', models.CharField(max_length=1000)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('father_Name', models.CharField(max_length=1000)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=1000)),
                ('emailid', models.CharField(max_length=1000)),
            ],
        ),
    ]
