# Generated by Django 4.0.3 on 2022-04-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Studentss',
        ),
    ]
