# Generated by Django 4.0.3 on 2022-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_rename_students_studentss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('father_Name', models.CharField(max_length=1000)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=1000)),
                ('emailid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Studentss',
        ),
    ]
